spring.application.name= food-service


spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12836405
server.port=9091
spring.datasource.username=sql12836405
spring.datasource.password=mqymEjTiSa

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=false


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


logging.file.name=logs/spring.log
logging.level.root=INFO
logging.level.com.food=INFO

#Maine security htayi hai aur username pw change kiya hai for db
#Add kiya hai application ka naam
spring.datasource.hikari.maximum-pool-size=2
